---
title: "Interactive Data Visualization in R with Shiny"
format:
  html:
   toc: true
---

Workshop materials and instructions for the *Interactive Data Visualization in R with Shiny* virtual workshop, led by JHU Data Services.

## Learning Objectives

> 1. Articulate basic principles of interactive data visualization 
>
> 2. Understand critical concepts from R-Shiny including the structure of a Shiny App, how to run a Shiny App, how to configure the aesthetics of a Shiny App, and how the reactive programming model of Shiny works. 
>
> 3. Be able to augment a barebones Shiny app framework to develop a fully functioning Shiny app using provided data. This will encompass R and HTML programming. 
>
> 4. Be able to identify tools and resources for sharing and deploying a Shiny app. Be aware of advanced style configuration using CSS. 
   

## Post-Class Survey

If you have taken the live webinar for this class, please take this survey: [Interactive Data Visualization in R with Shiny](https://bit.ly/shiny-r-vis-survey)

## Workshop Materials

### Presentation Slides

- [Presentation Slides (PDF)](PresentationMaterials/InteractiveVisualizationInRShiny.pdf)

### Completed Code

- [Day 1: Basic Shiny App](In-ClassScripts/part-1-basic-shiny-app.qmd)
- [Day 2: Penguin Dashboard](In-ClassScripts/part-2-penguin-dashboard.qmd)

### Cheatsheets

- [Base Graphics Cheatsheet](Resources/shiny-cheatsheet.pdf)

## Additional Data Visualization in R Resources

- [Additional Data Vis in R Resources](https://github.com/jhu-data-services/data-visualization-resources)

## JHU Data Services

Website: [dataservices.library.jhu.edu](https://dataservices.library.jhu.edu/)
Contact us: [dataservices@jhu.edu](mailto:dataservices@jhu.edu)

JHU Data Services, part of the Johns Hopkins University Sheridan Libraries, helps the JHU community find, use, visualize, manage, and share data. We offer live webinars and self-paced online trainings on computational research and coding, GIS, data management, data visualization, and more. [See all of our training topics on our website.](https://dataservices.library.jhu.edu/training-workshops/)

## License and Terms of Use

The presentation materials are licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/), attributable to [Data Services](https://dataservices.library.jhu.edu/), Johns Hopkins University.

See [LICENSE](LICENSE) file for additional code licensing and re-use information.

The images, external resources, and cheatsheets linked in this repository may have other licenses and terms of use.

## Citation

Please cite this material as:
Johns Hopkins University Data Services. March 20, 2026. [Interactive Data Visualization in R with Shiny](https://github.com/jhu-data-services/interactive-data-visualization-in-r-with-shiny)
